### ISSUE TITLE
Cannot get wirb to load; starting Wirb breaks everything with a TypeError

### ISSUE THREAD

**Issue by CPngN** [janlelis/wirb#10]
I have access to Rails console (Ruby 1.9.3, Rails 3.0.20) on our staging server to do interactive searches and run scripts, but cannot modify the main project (and thus cannot edit our Gemfile).

I've managed to get things like ap and wirble working by having .irbrc run through my own gems and load them all.  I can get wirb to install (as well as irbtools), but as soon as I try to do Wirb.start (or just Wirb all by itself!), I get this after the load attempt and almost everything else I try to do.  Any idea how to fix this? :

>> Wirb
=> Wirb
>> Wirb.start
TypeError: can't convert nil into String
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:60:in `join'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:60:in `load_schema!'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:81:in `load_schema'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:47:in `schema'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:98:in `colorize_result'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb/irb.rb:8:in `output_value'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:160:in `block (2 levels) in eval_input'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
	from /home/cnorman/gems/gems/binding.repl-1.0.4.1/lib/binding.repl/repls/irb.rb:9:in `block (2 levels) in <top (required)>'
... 14 levels...
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:70:in `block in start'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:69:in `catch'
	from /opt/ruby-1.9.3-p448/lib/ruby/1.9.1/irb.rb:69:in `start'
	from /enphase/enlighten/releases/20140616222008/vendor/bundle/ruby/1.9.1/gems/railties-3.0.20/lib/rails/commands/console.rb:44:in `start'
	from /enphase/enlighten/releases/20140616222008/vendor/bundle/ruby/1.9.1/gems/railties-3.0.20/lib/rails/commands/console.rb:8:in `start'
	from /enphase/enlighten/releases/20140616222008/vendor/bundle/ruby/1.9.1/gems/railties-3.0.20/lib/rails/commands.rb:23:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'Maybe IRB bug!

>> Address
TypeError: can't convert nil into String
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:60:in `join'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:60:in `load_schema!'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:81:in `load_schema'
	from /home/cnorman/gems/gems/wirb-1.0.3/lib/wirb.rb:47:in `schema'
etc
_________
The LOAD_PATH hack that I use to load wirble and awesome_print is from https://gist.github.com/skojin/794915
I also tried https://github.com/keithpitt/dotfiles/blob/master/dots/irbrc with same crash results using "require" or the special "unbundled_require".

Thanks!  Hoping I can finally use wirb this year!!

**Comment by janlelis** [comment]
Closing. Please re-open if still a problem.
