### ISSUE TITLE
wirb requires Ruby version ~> 2.0.

### ISSUE THREAD

**Issue by DanielBlanco** [janlelis/wirb#11]
According with Readme Wirb supports the following rubies: 2.2, 2.1, 2.0, jruby, rubinius.

but gemspec only supports Ruby `~> 2.0`, see https://github.com/janlelis/wirb/blob/master/wirb.gemspec#L12

please make it `>= 2.0`

**Comment by janlelis** [comment]
Hey @DanielBlanco,

please clarify which Ruby version does not work with the current WIRB.

`~> 2.0` should cover `2.0`, `2.1`, as well as `2.2` and newer (below 3.0)

**Comment by DanielBlanco** [comment]
Closing, it works fine. Maybe it was a stupid thing I did with my rvm.

Sorry for the troubles.
