### ISSUE TITLE
Big performance impact

### ISSUE THREAD

**Issue by ghost** [janlelis/wirb#5]
Returning a large array of an expression takes several minutes to finish on my Core 2 Duo machine.

irb(main):005:0> res= Array.new(10**6,1)

If Wirb is disabled, the above expression completes almost instantly.

**Comment by janlelis** [comment]
Wirb 2.0 comes with a timeout option. If Wirb is not fast enough to render the colored string in a few seconds, it willl output the uncolored original one.
